# Use an official OpenJDK runtime as a base image
FROM openjdk:17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file generated by Spring Boot build into the container
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
# Copy the JAR file generated by your Spring Boot build to the container
COPY target/chat-application-1.jar app.jar
# Expose the port your Spring Boot application listens on (adjust as needed)
EXPOSE 8080

# Command to run your Spring Boot application
CMD ["java", "-jar", "app.jar"]
